language: c++

sudo: required

compiler:
  - gcc
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

  #Codecov
  - sudo pip install codecov
  - chmod +x .get_code_cov.sh

install:
 
  #Codecov
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script:
  #Compile without optimization and with coverage
  - make test
  #Run the program
  - cd bin/
  - ./application test
  - cd ..
  #Codecov
  - ./.get_code_cov.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"